name: Deploy Proshop CI
on: [push, workflow_dispatch]
# on:
#   - push
#   -  workflow_dispatch
#  push:
#     branches: [master ]
#  pull_request:
#     branches: [master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    #  MONGO_URL: mongodb://localhost/order  -  details - to be added - to avoid polluting data in prodcution
    strategy:
      matrix:
        node-version: [22.x] # will run alos on with two node version - two jobs will run
        # mongodb-version: ['8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      #  - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.12.1
      #   with:
      #     mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install
        working-directory: frontend #  run inside frontend folder

      # - name: Run tests
      #   run: npm test
      #   working-directory: frontend
