name: Deploy Proshop CI
on: [push, workflow_dispatch]
# on:
#   - push
#   -  workflow_dispatch
#  push:
#     branches: [master ]
#  pull_request:
#     branches: [master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: frontend # ðŸ‘ˆ run inside frontend folder

      - name: Run tests
        run: npm test
        working-directory: frontend
