name: Deploy Proshop
on: [push, workflow_dispatch]
# on:
#   - push
#   - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6 # got from marketplace github - inbuild inse want to aovide mannul code as written below
        # run: |
        #   echo "cloning repo..."
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git
